version: '3.8'

services:
  jenkins:
    build: ./jenkins
    user: jenkins
    ports:
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins-data:/var/jenkins_home
      - /home/ubuntu/S12P11B105/nginx/conf.d:/var/jenkins_home/workspace/jenkinsTest/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro  # 호스트 머신의 인증서 마운트
    environment:
      - JAVA_OPTS=-Djava.awt.headless=true
    privileged: true


volumes:
  jenkins_home: